# Generated by Django 4.1.7 on 2023-04-09 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0003_rename_profile_pic_fcuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.ImageField(upload_to='')),
                ('currentstats', models.ImageField(upload_to='')),
                ('userfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.fcuser')),
            ],
        ),
    ]
