# Generated by Django 4.1.7 on 2023-04-16 15:58

import datetime
from django.db import migrations, models
import myfinance.models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.AddField(
            model_name='analytics',
            name='last_updated',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 16), max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='currentstats',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=myfinance.models.get_current_stats_path),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='stats',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=myfinance.models.get_stats_csv_path),
        ),
    ]
