# Generated by Django 4.1.7 on 2023-05-24 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0002_delete_userdata_analytics_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='last_updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, max_length=25, null=True),
        ),
    ]
