# Generated by Django 4.1.7 on 2023-07-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0003_alter_analytics_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='analytics',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
