# Generated by Django 4.1.7 on 2023-07-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0004_analytics_expenses_analytics_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='saving_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
