# Generated by Django 4.1.7 on 2023-04-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_rename_user_pic_fcuser_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
